<?php
require_once 'PHPUnit/Framework.php';

require_once '../lib/ApeAbstractConnection.php';
require_once '_files/ApeAbstractConnectionStub.php';
require_once '../lib/ApeClient.php';
require_once '../lib/ApeRequest.php';

/**
 * Test class for ApeClient.
 * Generated by PHPUnit on 2010-03-08 at 16:59:25.
 */
class ApeClientTest extends PHPUnit_Framework_TestCase {

    protected 
    	$connection,
    	$client;  

    protected function setUp(){
    	$this->connection = new ApeAbstractConnectionStub('somehost', 1234, 'https');
    	$this->client = new ApeClient($this->connection);		
    }
    
    public function testConstruction(){
         $this->assertTrue($this->client instanceof ApeClient);	   	
    } 


    public function testSendRequest(){
		$res = $this->client->sendRequest(new ApeRequest('foo'));
		$response = new ApeResponse(ApeAbstractConnectionStub::$defaultResponse);
    	$this->assertEquals($response, $res);
    }

    public function testDispatchRequest(){
		$res = $this->client->dispatchRequest('foo');
		$response = new ApeResponse(ApeAbstractConnectionStub::$defaultResponse);
    	$this->assertEquals($response, $res);
    }

}
?>
