<?php
require_once 'PHPUnit/Framework.php';

require_once '../lib/ApeException.php';

/**
 * Test class for ApeException.
 * Generated by PHPUnit on 2010-03-08 at 16:59:25.
 */
class ApeExceptionTest extends PHPUnit_Framework_TestCase
{
  
    public function testConstruction(){
        $e = new ApeException('foo');
        $this->assertEquals('foo', $e->getMessage());       
    }

    public function testThrow(){
        try {
        	throw new ApeException('foo');	
        }
        catch(ApeException $e){
        	return;
        }
    	$this->fail('ApeException has not been thrown');      
    }
    
    
}
?>
